#!/usr/bin/env python3
"""Fabrication guard, layer 3 of 4: deterministic drafting.

The renderer receives ONLY validated evidence (URL-verified by
validate_urls.py) and makes no model or tool call. It therefore cannot invent
or fetch sources it was never given. lint_post.py (layer 4) then rejects any
URL that is not in the validated evidence set.
"""

import json
import os
from pathlib import Path

import yaml

REPO_ROOT = Path(os.environ["REPO_ROOT"])
RUN_ID = os.environ["RUN_ID"]
RUN_DATE = os.environ["RUN_DATE"]
def load_new_evidence():
    items = {}
    for path in sorted((REPO_ROOT / "evidence").glob("EM-*.yaml")):
        loaded = yaml.safe_load(path.read_text(encoding="utf-8"))
        if not isinstance(loaded, list):
            continue
        pid = path.stem
        for entry in loaded:
            if isinstance(entry, dict) and entry.get("run_id") == RUN_ID:
                items.setdefault(pid, []).append(
                    {
                        "prediction_id": pid,
                        "claim": entry.get("claim", ""),
                        "url": entry.get("url", ""),
                        "date": entry.get("date", ""),
                        "quote_fragment": entry.get("quote_fragment", ""),
                    }
                )
    return items


def render_body(predictions, evidence_by_prediction):
    sections = []
    for prediction in predictions:
        pid = prediction["id"]
        sections.append(f"## {pid}")
        sections.append("")
        sections.append(prediction["statement"])
        sections.append("")
        evidence = evidence_by_prediction.get(pid, [])
        if not evidence:
            sections.append("No verifiable evidence surfaced this week.")
        else:
            sections.append("New evidence this week:")
            sections.append("")
            for item in evidence:
                date = item["date"] or "date unavailable"
                sections.append(f"- [{item['claim']}]({item['url']}) — {date}")
        sections.append("")
    return "\n".join(sections).rstrip()


def main():
    predictions = [
        {"id": p["id"], "statement": p.get("statement", "")}
        for p in yaml.safe_load((REPO_ROOT / "predictions.yaml").read_text(encoding="utf-8"))
        if isinstance(p, dict) and p.get("status") == "open"
    ]
    summary = json.loads(
        (REPO_ROOT / "evidence" / "_incoming" / RUN_ID / "summary.json").read_text(encoding="utf-8")
    )
    body = render_body(predictions, load_new_evidence())

    post = (
        f"<!-- DRAFT generated by mirror-ledger {RUN_ID}. NOT published. "
        f"Paul reviews and publishes manually; the pipeline never publishes. -->\n"
        f"# Ledger Update — {RUN_DATE}\n\n"
        f"{body}\n\n---\n"
        f"*Pipeline receipt: {summary['gathered']} evidence items gathered, "
        f"{summary['validated']} passed URL verification, {summary['rejected']} dropped "
        f"(drops logged in `evidence/_rejected.log`). Attestation: `receipts/{RUN_ID}.json`.*\n"
    )
    out = REPO_ROOT / "posts" / f"{RUN_DATE}.md"
    out.write_text(post, encoding="utf-8")
    print(f"[draft] wrote {out}")


if __name__ == "__main__":
    main()
