#!/usr/bin/env python3
"""Fabrication guard, layer 3 of 4: the drafter never touches the web.

The drafting call receives ONLY validated evidence (URL-verified by
validate_urls.py) and runs with no tools permitted, so it cannot invent or
fetch sources it was never given. The post footer is computed by this script,
not by the model. lint_post.py (layer 4) then rejects any URL that is not in
the validated evidence set.
"""

import json
import os
import subprocess
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(os.environ["REPO_ROOT"])
RUN_ID = os.environ["RUN_ID"]
RUN_DATE = os.environ["RUN_DATE"]
CLAUDE_BIN = os.environ.get("CLAUDE_BIN", "/Users/pauldesai/bin/claude")
MODEL = os.environ.get("MODEL", "claude-opus-4-6")
DRAFT_TIMEOUT = int(os.environ.get("GATHER_TIMEOUT", "600"))

INSTRUCTIONS = """You are drafting the weekly "Ledger Update" post for a public forecast ledger. You are given the open predictions and ONLY the evidence items that passed live-URL verification this week.

Write a markdown post body:
- One short section per open prediction: its id and statement (verbatim), then either "New evidence this week:" bullets or exactly "No verifiable evidence surfaced this week."
- Each bullet must cite one of the provided evidence items with its URL in markdown link form, its date, and a one-line reading of what it means for the prediction.
- Do not change or restate probabilities as your own judgment; scoring is the human's job. You may note direction ("leans confirming/invalidating/neutral").
- Use ONLY the provided evidence. Introducing any URL, publication, quote, or factual claim not present in the payload is a hard failure.
- No tickers, no share prices, no buy/sell language. Events, filings, and outcomes only.
- Under 700 words. Output ONLY the markdown body — no preamble, no code fences.

PAYLOAD:
"""


def load_new_evidence():
    items = []
    for path in sorted((REPO_ROOT / "evidence").glob("EM-*.yaml")):
        loaded = yaml.safe_load(path.read_text(encoding="utf-8"))
        if not isinstance(loaded, list):
            continue
        pid = path.stem
        for entry in loaded:
            if isinstance(entry, dict) and entry.get("run_id") == RUN_ID:
                items.append(
                    {
                        "prediction_id": pid,
                        "claim": entry.get("claim", ""),
                        "url": entry.get("url", ""),
                        "date": entry.get("date", ""),
                        "quote_fragment": entry.get("quote_fragment", ""),
                    }
                )
    return items


def main():
    predictions = [
        {
            "id": p["id"],
            "statement": p.get("statement", ""),
            "probability": p.get("probability"),
            "resolve_by": str(p.get("resolve_by", "")),
        }
        for p in yaml.safe_load((REPO_ROOT / "predictions.yaml").read_text(encoding="utf-8"))
        if isinstance(p, dict) and p.get("status") == "open"
    ]
    summary = json.loads(
        (REPO_ROOT / "evidence" / "_incoming" / RUN_ID / "summary.json").read_text(encoding="utf-8")
    )
    payload = {"week_of": RUN_DATE, "predictions": predictions, "new_evidence": load_new_evidence()}
    prompt = INSTRUCTIONS + json.dumps(payload, ensure_ascii=False, indent=2)

    child_env = dict(os.environ)
    child_env.pop("ANTHROPIC_API_KEY", None)  # subscription lane only

    # No --allowed-tools: in headless -p mode nothing is permitted, so the
    # drafter cannot search, fetch, read, or write anything.
    proc = subprocess.run(
        [CLAUDE_BIN, "-p", prompt, "--output-format", "json", "--model", MODEL],
        capture_output=True,
        text=True,
        timeout=DRAFT_TIMEOUT,
        env=child_env,
        cwd=str(REPO_ROOT),
    )
    if proc.returncode != 0:
        print(f"[draft] claude exit {proc.returncode}: {(proc.stderr or '')[:400]}", file=sys.stderr)
        raise SystemExit(1)
    try:
        envelope = json.loads(proc.stdout)
        body = envelope.get("result", "") if isinstance(envelope, dict) else proc.stdout
    except json.JSONDecodeError:
        body = proc.stdout
    body = (body or "").strip()
    if not body:
        print("[draft] empty draft body", file=sys.stderr)
        raise SystemExit(1)

    post = (
        f"<!-- DRAFT generated by mirror-ledger {RUN_ID}. NOT published. "
        f"Paul reviews and publishes manually; the pipeline never publishes. -->\n"
        f"# Ledger Update — {RUN_DATE}\n\n"
        f"{body}\n\n---\n"
        f"*Pipeline receipt: {summary['gathered']} evidence items gathered, "
        f"{summary['validated']} passed URL verification, {summary['rejected']} dropped "
        f"(drops logged in `evidence/_rejected.log`). Attestation: `receipts/{RUN_ID}.json`.*\n"
    )
    out = REPO_ROOT / "posts" / f"{RUN_DATE}.md"
    out.write_text(post, encoding="utf-8")
    print(f"[draft] wrote {out}", file=sys.stderr)


if __name__ == "__main__":
    main()
